server:
  servlet:
    session:
      timeout: 86400
    contextPath: ${CONTEXT_PATH:/template}
  port: ${SERVER_PORT:8082}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/stream+json
  forward-headers-strategy: framework

spring:
  datasource:
    username: ${CONFIG_DB_USER}
    password: ${CONFIG_DB_PASSWORD}
    url: jdbc:postgresql://${CONFIG_DB_POSTGRES_HOST}/${CONFIG_DATABASE}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${CONFIG_MAX_POOL_SIZE:5}
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true
    table: schema_version
    fail-on-missing-locations: true
